{
  "title": "金牌影院",
  "host": "https://m.sunnafh.com",
  "url": "/api/mw-movie/anonymous/video/list?pageNum=fypage&pageSize=30&sort=fyorder&sortBy=1&type1=fyclass&type=fytype&class=fyplot&area=fyarea&year=fyyear&lang=fylang",
  "searchUrl": "/api/mw-movie/anonymous/video/searchByWordPageable?keyword=**&pageNum=fypage&pageSize=12&type=false",
  "headers": {
    "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 18_2_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.2 Mobile/15E148 Safari/604.1"
  },
  "searchable": 2,
  "quickSearch": 0,
  "filterable": 1,
  "limit": 30,
  "double": false,
  "play_parse": true,
  "class_name": "电影&电视剧&综艺&动漫",
  "class_url": "1&2&3&4",
  "filter_def": {
    "fyorder": [
      {"name":"默认排序","value":"1"},
      {"name":"最近更新","value":"2"},
      {"name":"人气优先","value":"3"},
      {"name":"评分优先","value":"4"}
    ],
    "fytype": [
      {"name":"全部","value":""},
      {"name":"喜剧","value":"22"},
      {"name":"动作","value":"23"},
      {"name":"科幻","value":"30"},
      {"name":"爱情","value":"26"},
      {"name":"悬疑","value":"27"},
      {"name":"奇幻","value":"87"},
      {"name":"剧情","value":"37"},
      {"name":"恐怖","value":"36"},
      {"name":"犯罪","value":"35"},
      {"name":"动画","value":"33"},
      {"name":"惊悚","value":"34"},
      {"name":"战争","value":"25"},
      {"name":"冒险","value":"31"},
      {"name":"灾难","value":"81"},
      {"name":"伦理","value":"83"},
      {"name":"其他","value":"43"}
    ],
    "fyplot": [
      {"name":"全部","value":""},
      {"name":"爱情","value":"爱情"},
      {"name":"动作","value":"动作"},
      {"name":"喜剧","value":"喜剧"},
      {"name":"战争","value":"战争"},
      {"name":"科幻","value":"科幻"},
      {"name":"剧情","value":"剧情"},
      {"name":"武侠","value":"武侠"},
      {"name":"冒险","value":"冒险"},
      {"name":"枪战","value":"枪战"},
      {"name":"恐怖","value":"恐怖"},
      {"name":"其他","value":"其他"}
    ],
    "fyarea": [
      {"name":"全部地区","value":""},
      {"name":"中国大陆","value":"中国大陆"},
      {"name":"中国香港","value":"中国香港"},
      {"name":"中国台湾","value":"中国台湾"},
      {"name":"美国","value":"美国"},
      {"name":"日本","value":"日本"},
      {"name":"韩国","value":"韩国"},
      {"name":"印度","value":"印度"},
      {"name":"泰国","value":"泰国"},
      {"name":"英国","value":"英国"},
      {"name":"法国","value":"法国"},
      {"name":"其他","value":"其他"}
    ],
    "fyyear": [
      {"name":"全部年份","value":""},
      {"name":"2026","value":"2026"},
      {"name":"2025","value":"2025"},
      {"name":"2024","value":"2024"},
      {"name":"2023","value":"2023"},
      {"name":"2022","value":"2022"},
      {"name":"2021","value":"2021"},
      {"name":"2020","value":"2020"},
      {"name":"2019","value":"2019"},
      {"name":"2018","value":"2018"},
      {"name":"2017","value":"2017"},
      {"name":"2016","value":"2016"},
      {"name":"2015","value":"2015"},
      {"name":"2014","value":"2014"},
      {"name":"2013","value":"2013"},
      {"name":"2012","value":"2012"},
      {"name":"2011","value":"2011"},
      {"name":"2010","value":"2010"},
      {"name":"2009~2000","value":"2009~2000"}
    ],
    "fylang": [
      {"name":"全部语言","value":""},
      {"name":"国语","value":"国语"},
      {"name":"英语","value":"英语"},
      {"name":"粤语","value":"粤语"},
      {"name":"韩语","value":"韩语"},
      {"name":"日语","value":"日语"},
      {"name":"泰语","value":"泰语"},
      {"name":"其他","value":"其他"}
    ]
  },
  "一级": "js:\nlet d = [];\nlet t = new Date().getTime();\neval(getCryptoJS);\nlet signkey = input.split('?')[1]+'&key=cb808529bae6b6be45ecfab29a4889bc&t='+t;\nlet key = CryptoJS.SHA1(CryptoJS.MD5(signkey).toString()).toString();\nlet res = JSON.parse(request(input,{\nheaders:{\n'User-Agent':'Mozilla/5.0 (iPhone; CPU iPhone OS 18_2_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.2 Mobile/15E148 Safari/604.1',\ndeviceId:'63ffad23-a598-4f96-85d7-7bf5f3e4a0a2',\nsign:key,\nt:t\n}\n})).data.list;\nres.forEach(it=>{\n  d.push({\n    title:it.vodName,\n    desc:it.vodRemarks||it.vodDoubanScore,\n    img:it.vodPic,\n    url:'http'+it.vodId\n  })\n});\nsetResult(d);",
  "二级": "js:\nlet kid=input.split('http')[1];\nlet t = new Date().getTime();\neval(getCryptoJS);\nlet signkey='id='+kid+'&key=cb808529bae6b6be45ecfab29a4889bc&t='+t;\nlet key=CryptoJS.SHA1(CryptoJS.MD5(signkey).toString()).toString();\nlet kjson=JSON.parse(request('https://m.sunnafh.com/api/mw-movie/anonymous/video/detail?id='+kid,{\nheaders:{\n'User-Agent':'Mozilla/5.0 (iPhone; CPU iPhone OS 18_2_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.2 Mobile/15E148 Safari/604.1',\ndeviceId:'63ffad23-a598-4f96-85d7-7bf5f3e4a0a2',\nsign:key,\nt:t\n}\n})).data;\nlet kurls = kjson.episodeList.map(it=>it.name+'$https://m.sunnafh.com/vod/play/'+kid+'/sid/'+it.nid).join('#');\nVOD={\nvod_id:kid,\nvod_name:kjson.vodName,\nvod_pic:kjson.vodPic,\ntype_name:kjson.vodClass,\nvod_remarks:kjson.vodRemarks,\nvod_year:kjson.vodYear,\nvod_area:kjson.vodArea,\nvod_lang:kjson.vodLang,\nvod_director:kjson.vodDirector,\nvod_actor:kjson.vodActor,\nvod_content:kjson.vodContent,\nvod_play_from:'金牌线路',\nvod_play_url:kurls\n}",
  "lazy": "js:\nlet pid = input.split('/')[5];\nlet nid = input.split('/')[7];\nconst t = new Date().getTime();\neval(getCryptoJS);\nlet signkey = 'clientType=1&id='+pid+'&nid='+nid+'&key=cb808529bae6b6be45ecfab29a4889bc&t='+t;\nconst key = CryptoJS.SHA1(CryptoJS.MD5(signkey).toString()).toString();\nlet json_data = JSON.parse(request('https://m.sunnafh.com/api/mw-movie/anonymous/v2/video/episode/url?clientType=1&id='+pid+'&nid='+nid,{\nheaders:{\n'User-Agent':'Mozilla/5.0 (iPhone; CPU iPhone OS 18_2_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.2 Mobile/15E148 Safari/604.1',\ndeviceid':'63ffad23-a598-4f96-85d7-7bf5f3e4a0a2',\nsign:key,\nt:t\n}\n}));\nlet link = json_data.data.list[0].url;\nif(/\\.(m3u8|mp4)/.test(link)){input={jx:0,parse:0,url:link}}else{input={jx:0,parse:1,url:link}}",
  "搜索": "js:\nlet t = new Date().getTime();\neval(getCryptoJS);\nlet pg = MY_PAGE;\nlet signkey = 'keyword='+KEY+'&pageNum='+pg+'&pageSize=12&type=false&key=cb808529bae6b6be45ecfab29a4889bc&t='+t;\nlet key = CryptoJS.SHA1(CryptoJS.MD5(signkey).toString()).toString();\nlet html = JSON.parse(request(input,{\nheaders:{\n'User-Agent':'Mozilla/5.0 (iPhone; CPU iPhone OS 18_2_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.2 Mobile/15E148 Safari/604.1',\ndeviceid':'63ffad23-a598-4f96-85d7-7bf5f3e4a0a2',\nsign:key,\nt:t\n}\n}));\nlet data = html.data.list;\nlet d = [];\ndata.forEach(it=>{\n  d.push({\n    title:it.vodName,\n    desc:it.vodVersion||it.vodRemarks,\n    img:it.vodPic,\n    url:'http'+it.vodId\n  })\n});\nsetResult(d)"
}